home/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views
app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
    path('portfolio/', views.portfolio, name="portfolio"),
    re_path('project/(?P<slug>[\w-]+)/', views.project, name="project"),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class TitleSubtitle(models.Model):
    about_title = models.CharField(max_length=25, default='about me', blank=True, null=True)
    about_sub_title = models.CharField(max_length=255, default='', blank=True, null=True)
    service_title = models.CharField(max_length=25, default='services', blank=True, null=True)
    service_sub_title = models.CharField(max_length=255, default='', blank=True, null=True)
    portfolio_title = models.CharField(max_length=25, default='portfolio', blank=True, null=True)
    portfolio_sub_title = models.CharField(max_length=255, default='', blank=True, null=True)
    feedback_title = models.CharField(max_length=25, default='feedback', blank=True, null=True)
    feedback_sub_title = models.CharField(max_length=255, default='', blank=True, null=True)
    contact_title = models.CharField(max_length=25, default='contact me', blank=True, null=True)
    contact_sub_title = models.CharField(max_length=255, default='', blank=True, null=True)

class Home(models.Model):
    brand_name = models.CharField(max_length=25, default='', blank=True, null=True)
    up_heading = models.CharField(max_length= 255, default='', blank=True, null=True)
    down_heading = models.CharField(max_length= 255, default='', blank=True, null=True)
    button_text = models.CharField(max_length=255, default='Know More', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'home'

    def __str__(self):
        return self.brand_name

class About(models.Model):
    about = models.TextField(default='', blank=True, null=True)
    cv = models.FileField(upload_to='About/', default='About/NID-card.pdf', blank=True)

    class Meta:
        verbose_name_plural = 'About'

    def __str(self):
        return self.cv

class Skill(models.Model):
    skills = models.CharField(max_length=25, default='', blank=True, null=True)

    def __str__(self):
        return self.skills

class Service(models.Model):
    s_icon = models.ImageField(upload_to = 'ServiceIcon/', default='ServiceIcon/settings.png', blank=True)
    s_title = models.CharField(max_length=255, default='', blank=True, null=True)
    s_details = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.s_title

class Project(models.Model):
    project_name = models.CharField(max_length=50, default='Threads', blank=True, null=True)
    category = models.CharField(max_length=50, default='Illustration', blank=True, null=True)
    thumb_1 = models.ImageField(upload_to = 'Portfolio/%Y/%m/%d', blank=True)
    thumb_2 = models.ImageField(upload_to = 'Portfolio/%Y/%m/%d', blank=True)
    project_info = models.TextField(blank=True, null=True)
    clients = models.CharField(max_length=50, default='Brand & Co.', blank=True, null='True')
    tools = models.CharField(max_length=255, blank=True, null=True)
    live_url = models.URLField(max_length=255, blank=True, null=True)
    slug = models.SlugField(unique=True)
    status = models.CharField(max_length=50, default='', blank=True, null=True)

    def __str__(self):
        return self.project_name

    def _get_unique_slug(self):
        slug = slugify(self.project_name)
        unique_slug = slug
        num = 1
        while Project.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug,num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()


class Feedback(models.Model):
    photo = models.ImageField(upload_to="Feedback/%Y/%m/%d", blank=True)
    name = models.CharField(max_length=25, blank=True, null=True)
    profession = models.CharField(max_length=50, blank=True, null=True)
    comment = models.CharField(max_length=255)


class FollowMe(models.Model):
    facebook_id = models.CharField(max_length=50, default='', blank=True, null=True)
    facebook_url = models.URLField(max_length=255, default='https://www.facebook.com/', blank=True, null=True)
    twitter_id = models.CharField(max_length=50, default='', blank=True, null=True)
    twitter_url = models.URLField(max_length=255, default='https://www.twitter.com/', blank=True, null=True)
    linkedin_id = models.CharField(max_length=50, default='', blank=True, null=True)
    linkedin_url = models.URLField(max_length=255, default='https://www.linkedin.com/', blank=True, null=True)
    google_plus_id = models.CharField(max_length=50, default='', blank=True, null=True)
    google_plus_url = models.URLField(max_length=255, default='https://plus.google.com/', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Follow Me'

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()

    class Meta:
        verbose_name_plural = 'Contact'

    def __str__(self):
        return self.subject

home/forms.py
from django import forms
from .models import Project, Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length= 50, widget=forms.TextInput())
    email = forms.EmailField(max_length= 255, widget=forms.TextInput())
    subject = forms.CharField(max_length= 50, widget=forms.TextInput())
    message = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'subject',
            'message'
        ]


class ProjectForm(forms.ModelForm):
    project_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Project Name'}))
    category = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Category'}))
    project_info = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Project Info'}))
    clients = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Clients'}))
    tools = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Tools'}))
    live_url = forms.URLField(max_length=50, widget=forms.URLInput(attrs={'class':'form-control', 'placeholder':'Live URL'}))

    class Meta:
        model = Project
        fields = [
            'project_name',
            'category',
            'thumb_1',
            'thumb_2',
            'project_info',
            'clients',
            'tools',
            'live_url'
        ]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotFound
from .models import TitleSubtitle, Home, About, Skill, Service, Project, Feedback, FollowMe
from .forms import ProjectForm, ContactForm

def home(request):
    title_subtitle = TitleSubtitle.objects.filter(id=1)
    home_query = Home.objects.filter(id=1)
    about = About.objects.filter(id=1)
    skills = Skill.objects.all().order_by('skills')
    service = Service.objects.all().order_by('id')[:3]
    projects = Project.objects.all().order_by('-id')[:3]
    feedbacks = Feedback.objects.all().order_by('-id')[:3]
    follow_me = FollowMe.objects.filter(id=1)

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    else:
        form = ContactForm()

    context = {
        'title': title_subtitle,
        'home': home_query,
        'about': about,
        'skill': skills,
        'service': service,
        'project': projects,
        'feedback': feedbacks,
        'follow': follow_me,
        'form': form
    }

    return render(request, 'home/index.html', context)


def portfolio(request):
    title_subtitle = TitleSubtitle.objects.filter(id=1)
    projects = Project.objects.all().order_by('-id')

    context = {
        'title': title_subtitle,
        'project': projects
    }

    return render(request, 'home/portfolio.html', context)

def project(request, slug):
    instance = get_object_or_404(Project, slug=slug)
    context = {
        'i': instance,
    }
    return render(request, 'home/project.html', context)

home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block home %}
    <div class="bgimg" id="home">

      <nav class="navbar navbar-expand-md bg-dark navbar-drark fixed-top">
        <div class="container">
          {% for h in home %}
          <a href="#home" class="navbar-brand text-warning font-weight-bold">{{ h.brand_name }}</a>
          {% endfor %}
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsenavbar">
            <img src="{% static 'home/img/icons8-menu-24.png' %}" alt="">
          </button>

          <div class="collapse navbar-collapse text-center" id="collapsenavbar">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="#home" class="nav-link text-white active" data-scroll>Home</a>
              </li>
              <li class="nav-item">
                <a href="#about" class="nav-link text-white" data-scroll>About</a>
              </li>
              <li class="nav-item">
                <a href="#services" class="nav-link text-white" data-scroll>Services</a>
              </li>
              <li class="nav-item">
                <a href="#portfolio" class="nav-link text-white" data-scroll>Portfolio</a>
              </li>
              <li class="nav-item">
                <a href="#feedback" class="nav-link text-white" data-scroll>Feedback</a>
              </li>
              <li class="nav-item">
                <a href="#contact" class="nav-link text-white" data-scroll>Contact</a>
              </li>
            </ul>
          </div>

        </div><!-- home container end -->
      </nav><!-- home nav end -->

      <div class="container text-center text-white headerset">
        {% for h in home %}
        <h2 class="text-capitalize">{{ h.up_heading }}</h2>
        <h1 class="text-uppercase">{{ h.down_heading }}</h1>
        <a href="#about"><button type="button" class="btn btn-warning text-white btn-lg text-capitalize">{{ h.button_text }}</button></a>
        {% endfor %}
      </div>

    </div><!-- home div end -->


    <!--about me section start -->
    <section class="about" id="about">
      <div class="container">
        {% for t in title %}
        <h1 class="text-center text-capitalize">{{ t.about_title }}</h1>
        <p class="text-center">{{ t.about_sub_title }}</p>
        {% endfor %}
        <div class="row aboutsetting">

          {% for a in about %}
          <div class="about-me col-lg-6 col-md-6 col-sm-10 col-12 d-block m-auto text-justify">
            <h3>Hello,</h3>
            <p>{{ a.about }}</p>
            <a href="{{ a.cv.url }}"><button type="button" class="btn btn-warning text-white"> <i class="fa fa-download"></i> Download CV</button></a>
          {% endfor %}
            <a href="#contact"><button type="button" class="btn btn-outline-warning hire">Hire Me</button></a>
          </div>

          <div class="col-lg-2 col-md-1"></div>

          <div class="col-lg-4 col-md-5 col-sm-10 col-12 d-block m-auto text-center">
            <h3>Skills</h3>
            {% for s in skill %}
            <button type="button" class="btn btn-light" disabled>{{ s.skills }}</button>
            {% endfor %}
          </div>

        </div>

      </div>
    </section>


    <!--services section start-->
    <section id="services" class="services text-white" >
      <div class="container text-center">

        {% for t in title %}
        <h1 class="text-uppercase">{{ t.service_title }}</h1>
        <p>{{ t.service_sub_title }}</p>
        {% endfor %}

        <div class="row rowsetting">

          <!--single services start-->
          {% for s in service %}
          <div class="col-lg-4 col-md-4 col-sm-4 col-10 d-block m-auto wow slideInLeft">
            <div class="imgsetting d-block m-auto bg-warning">
              <img src="{{ s.s_icon.url }}" style="margin-top: 20px">
            </div>

            <h2 class="text-capitalize">{{ s.s_title }}</h2>
            <p>{{ s.s_details }}</p>
          </div>
          {% endfor %}

        </div><!-- services row rowsetting end -->

      </div>
    </section> <!-- services section end -->


    <!--portfolio section start-->
    <section id="portfolio" class="portfolio">

      <div class="container text-center">

        {% for t in title %}
        <h1 class="text-uppercase">{{ t.portfolio_title }}</h1>
        <p>{{ t.portfolio_sub_title }}</p>
        {% endfor %}

        <div class="row">
          {% for p in project %}
          <!--single portfolio start -->
          <div class="col-lg-4 col-md-4 col-sm-10 col-10 d-block m-auto">
            <div class="card">
              <div class="box">
                <img src="{{ p.thumb_1.url }}" class="card-img img-fluid" alt="">
                <div class="box-content">
                    <h3 class="title">Live Demo</h3>
                    <ul class="icon">
                        <li><a href="{{ p.live_url }}"><i class="fa fa-link"></i></a></li>
                    </ul>
                </div>
              </div>
              <div class="card-body">
                <a href="{% url 'home:project' slug=p.slug %}"><h2 class="card-title text-dark">{{ p.project_name }}</h2></a>
                <p class="card-text">{{ p.category }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <a href="{% url 'home:portfolio' %}"><button type="button" class="btn btn-warning text-white btn-lg">See More</button></a>

      </div><!--end of portfolio container-->

    </section><!--end of portfolio section-->

    <!-- fun-fact section start
    <section class="fun-fact">
      <div class="container text-center text-white">

        <div class="row">
          <div class="single-fun col-lg-3 col-md-3 col-sm-10 col-10 d-block m-auto">
            <i class="fa fa-check-square-o fa-3x" aria-hidden="true"></i>
            <span>758</span>
            <h4 class="text-uppercase">project completed</h4>
          </div>

          <div class="single-fun col-lg-3 col-md-3 col-sm-10 col-10 d-block m-auto">
            <i class="fa fa-smile-o fa-3x" aria-hidden="true"></i>
            <span>758</span>
            <h4 class="text-uppercase">project completed</h4>
          </div>

          <div class="single-fun col-lg-3 col-md-3 col-sm-10 col-10 d-block m-auto">
            <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
            <span>758</span>
            <h4 class="text-uppercase">project completed</h4>
          </div>

          <div class="single-fun col-lg-3 col-md-3 col-sm-10 col-10 d-block m-auto">
            <i class="fa fa-envelope-o fa-3x" aria-hidden="true"></i>
            <span>758</span>
            <h4 class="text-uppercase">project completed</h4>
          </div>
        </div>

      </div>
    </section> fun-fact section end-->

    <section id="feedback" class="clients">
      <div class="container text-center">

        {% for t in title %}
        <h1 class="text-uppercase">{{ t.feedback_title }}</h1>
        <p>{{ t.feedback_sub_title }}</p>
        {% endfor %}

        <div class="row clientssetting">
          <div class="col-lg-12 col-md-12 col-sm-12 col-12">

              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>

                <div class="carousel-inner">
                  {% for f in feedback %}
                  <div {% if forloop.first %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}>
                    <img class="img-fluid rounded-circle" height="100px" width="100px" src="{{ f.photo.url }}" alt="First slide">
                    <h4>{{ f.name }}, <span>{{ f.profession }}</span> </h4>
                    <p>{{ f.comment }}</p>
                  </div>
                  {% endfor %}
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <i class="text-dark fa fa-arrow-left fa-2x" style="font-size: 22px" aria-hidden="true"> </i>
                  <span class="sr-only">Previous</span>
                </a>

                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <i class="text-dark fa fa-arrow-right" style="font-size: 22px" aria-hidden="true"> </i>
                  <span class="sr-only">Next</span>
                </a>

              </div>

          </div>
        </div>

      </div>
    </section>


    <!--follow me section  start -->
    <section class="follow-me bg-dark text-white">
      <div class="container text-center">

        <div class="row follow-me-set">
          <div class="single-follow col-lg-3 col-md-3 col-sm-3 d-block m-auto">
            <i class="fa fa-facebook fa-2x"></i>
            {% for f in follow %}
            <a href="{{ f.facebook_url }}"><h4 class="text-white">{{ f.facebook_id }}</h4></a>
            {% endfor %}
          </div>

          <div class="single-follow col-lg-3 col-md-3 col-sm-3 d-block m-auto">
            <i class="fa fa-twitter fa-2x"></i>
            {% for f in follow %}
            <a href="{{ f.twitter_url }}"><h4 class="text-white">{{ f.twitter_id }}</h4></a>
            {% endfor %}
          </div>

          <div class="single-follow col-lg-3 col-md-3 col-sm-3 d-block m-auto">
            <i class="fa fa-linkedin fa-2x"></i>
            {% for f in follow %}
            <a href="{{ f.linkedin_url }}"><h4 class="text-white">{{ f.linkedin_id }}</h4></a>
            {% endfor %}
          </div>

          <div class="col-lg-3 col-md-3 col-sm-3  d-block m-auto">
            <i class="fa fa-google-plus fa-2x"></i>
            {% for f in follow %}
            <a href="{{ f.google_plus_url }}"><h4 class="text-white">{{ f.google_plus_id }}</h4></a>
            {% endfor %}
          </div>
        </div>

      </div>
    </section>


    <!-- contact section start-->
    <section id="contact" class="contact">
      <div class="container text-center">

        {% for t in title %}
        <h1 class="text-uppercase">{{ t.contact_title }}</h1>
        <p>{{ t.contact_sub_title }}</p>
        {% endfor %}

        <div class="row contactsetting">
          <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-4 col-sm-12 col-12 d-block m-auto">
                <input type="text" name="name" class="form-control" placeholder="Name" maxlength="50" required id="id_name">
              </div>
              <div class="form-group col-md-4 col-sm-12 col-12 d-block m-auto">
                <input type="email" name="email" class="form-control" placeholder="Email" maxlength="50" required id="id_email">
              </div>
              <div class="form-group col-md-4 col-sm-12 col-12 d-block m-auto">
                <input type="text" name="subject" class="form-control" placeholder="Subject" maxlength="50" required id="id_subject">
              </div>
              <div class="form-group col-md-12 col-sm-12 col-12 d-block m-auto">
                <textarea rows="8" cols="80" name="message" class="form-control" maxlength="50" required id="id_message">Message</textarea>
              </div>
            </div>
            <input type="submit" class="btn btn-warning text-white btn-lg" value="Send">
          </form>
        </div>

      </div>
    </section>


{% endblock %}

home/templates/home/portfolio.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/project.css' %}">
{% endblock %}

{% block portfolio %}
  <header class="portfolio-banner" id="home">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <div class="container">
        <a href="{% url 'home:home' %}" class="navbar-brand text-warning font-weight-bold">Nae'3m</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsenavbar">
          <img src="{% static 'home/img/icons8-menu-24.png' %}" alt="">
        </button>

        <div class="collapse navbar-collapse text-center" id="collapsenavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Home</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">About</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Services</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:portfolio' %}" class="nav-link text-white active">Portfolio</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Feedback</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container text-left text-white portfolioset">
      {% for t in title %}
      <h2 class="text-capitalize">{{ t.portfolio_title }}</h2>
      <span>{{ t.portfolio_sub_title }}</span>
      {% endfor %}
    </div>
  </header>

  <!--portfolio section start-->
  <section id="portfolio" class="portfolio">

    <div class="container text-center">

      <h1 class="text-uppercase">Portfolio</h1>
      <p>Expertise with world class work quality</p>

      <div class="row">
        {% for p in project %}
        <!--single portfolio start -->
        <div class="col-lg-4 col-md-4 col-sm-10 col-10 d-block m-auto">
          <div class="card">
            <div class="box">
              <img src="{{ p.thumb_1.url }}" class="card-img img-fluid" alt="">
              <div class="box-content">
                  <h3 class="title">Live Demo</h3>
                  <ul class="icon">
                      <li><a href="{{ p.live_url }}"><i class="fa fa-link"></i></a></li>
                  </ul>
              </div>
            </div>
            <div class="card-body">
              <a href="{% url 'home:project' slug=p.slug %}"><h2 class="card-title text-dark">{{ p.project_name }}</h2></a>
              <p class="card-text">{{ p.category }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div><!--end of portfolio container-->

  </section><!--end of portfolio section-->
{% endblock %}

home/templates/home/project.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'home/css/project.css' %}">
{% endblock %}

{% block project %}
  <header class="project-banner" id="home">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <div class="container">
        <a href="#" class="navbar-brand text-warning font-weight-bold">Nae'3m</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsenavbar">
          <img src="{% static 'home/img/icons8-menu-24.png' %}" alt="">
        </button>

        <div class="collapse navbar-collapse text-center" id="collapsenavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Home</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">About</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Services</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:portfolio' %}" class="nav-link text-white active">Portfolio</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Feedback</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container text-left text-white portfolioset">
      <h2>{{ i.project_name }}</h2>
      <span>{{ i.clients }} | {{ i.category }}</span>
    </div>
  </header>

  <section class="section-main">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-6 col-10 d-block m-auto">
          <div class="slider-img">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{{ i.thumb_1.url }}" alt="First slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{{ i.thumb_2.url }}" alt="Second slide">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <i class="text-dark fa fa-chevron-left " style="font-size: 22px" aria-hidden="true"> </i>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <i class="text-dark fa fa-chevron-right " style="font-size: 22px" aria-hidden="true"> </i>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row" style="margin-top: 50px">
        <div class="col-lg-8 col-md-8 col-sm-6 col-10 d-block m-auto">
          <div class="portfolio-spec">
            <div class="single-spec">
              <h4 class="text-uppercase">Project Info</h4>
              <p>{{ i.project_info }}</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-6 col-10 d-block m-auto">
          <div class="portfolio-spec">
              <div class="single-spec">
                <h4 class="text-uppercase">clients</h4>
                <p>{{ i.clients }}</p>
              </div>
              <div class="single-spec">
                <h4 class="text-uppercase">tools</h4>
                <p>{{ i.tools }}</p>
              </div>
              <div class="single-spec">
                <h4 class="text-uppercase">status</h4>
                <p>{{ i.status }}</p>
              </div>
              <div class="single-spec">
                <h4 class="text-uppercase">live url</h4>
                <p><a href="{{ i.live_url }}" class="text-warning">{{ i.live_url }}</a></p>
              </div>
              <!--<div class="single-spec">
                <h4 class="text-uppercase">share</h4>
                <p>
                  <i class="fa fa-facebook"></i>
                  <i class="fa fa-twitter"></i>
                  <i class="fa fa-google-plus"></i>
                </p>
              </div>-->
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}